from __future__ import annotations


ICON_ALIASES = {
    "add": "fa5s.plus",
    "app": "fa5s.cube",
    "api": "fa5s.project-diagram",
    "archive": "fa5s.archive",
    "back": "fa5s.chevron-left",
    "bell": "fa5s.bell",
    "book": "fa5s.book",
    "bookmark": "fa5s.bookmark",
    "bug": "fa5s.bug",
    "calendar": "fa5s.calendar-alt",
    "cancel": "fa5s.ban",
    "chart": "fa5s.chart-line",
    "check": "fa5s.check",
    "chevron_down": "fa5s.chevron-down",
    "chevron_left": "fa5s.chevron-left",
    "chevron_right": "fa5s.chevron-right",
    "chevron_up": "fa5s.chevron-up",
    "clear": "fa5s.trash",
    "close": "fa5s.times",
    "cloud": "fa5s.cloud",
    "code": "fa5s.code",
    "color": "fa5s.palette",
    "copy": "fa5s.copy",
    "database": "fa5s.database",
    "delete": "fa5s.trash",
    "desktop": "fa5s.desktop",
    "document": "fa5s.file-alt",
    "down": "fa5s.chevron-down",
    "download": "fa5s.download",
    "dialog": "fa5s.info-circle",
    "edit": "fa5s.edit",
    "error": "fa5s.times-circle",
    "export": "fa5s.file-export",
    "eye": "fa5s.eye",
    "eye_off": "fa5s.eye-slash",
    "file": "fa5s.file",
    "filter": "fa5s.filter",
    "folder": "fa5s.folder",
    "folder_open": "fa5s.folder-open",
    "flyout": "fa5s.comment-alt",
    "gear": "fa5s.cog",
    "grid": "fa5s.th-large",
    "help": "fa5s.question-circle",
    "history": "fa5s.history",
    "home": "fa5s.home",
    "image": "fa5s.image",
    "import": "fa5s.file-import",
    "info": "fa5s.info-circle",
    "key": "fa5s.key",
    "layers": "fa5s.layer-group",
    "link": "fa5s.external-link-alt",
    "list": "fa5s.list",
    "loading": "fa5s.spinner",
    "lock": "fa5s.lock",
    "mail": "fa5s.envelope",
    "menu": "fa5s.ellipsis-h",
    "message": "fa5s.comment-alt",
    "minus": "fa5s.minus",
    "more": "fa5s.ellipsis-h",
    "next": "fa5s.chevron-right",
    "notification": "fa5s.bell",
    "open": "fa5s.external-link-alt",
    "palette": "fa5s.palette",
    "pause": "fa5s.pause",
    "person": "fa5s.user",
    "pin": "fa5s.thumbtack",
    "play": "fa5s.play",
    "plus": "fa5s.plus",
    "previous": "fa5s.chevron-left",
    "print": "fa5s.print",
    "python": "fa5b.python",
    "refresh": "fa5s.sync-alt",
    "remove": "fa5s.minus",
    "reset": "fa5s.undo",
    "rocket": "fa5s.rocket",
    "save": "fa5s.save",
    "search": "fa5s.search",
    "send": "fa5s.paper-plane",
    "server": "fa5s.server",
    "settings": "fa5s.cog",
    "shield": "fa5s.shield-alt",
    "star": "fa5s.star",
    "success": "fa5s.check-circle",
    "sync": "fa5s.sync-alt",
    "table": "fa5s.table",
    "tag": "fa5s.tag",
    "terminal": "fa5s.terminal",
    "time": "fa5s.clock",
    "token": "fa5s.key",
    "tree": "fa5s.sitemap",
    "toast": "fa5s.bell",
    "unlock": "fa5s.unlock",
    "up": "fa5s.chevron-up",
    "upload": "fa5s.upload",
    "user": "fa5s.user",
    "users": "fa5s.users",
    "warning": "fa5s.exclamation-triangle",
    "window": "fa5s.window-restore",
}


DEFAULT_WINDOW_ICON = "app"

WINDOW_ICON_ALIASES = {
    "app": "app",
    "color": "color",
    "dialog": "dialog",
    "flyout": "flyout",
    "folder": "folder",
    "menu": "menu",
    "message": "message",
    "splash": "rocket",
    "toast": "toast",
    "window": "window",
}


__all__ = ["DEFAULT_WINDOW_ICON", "ICON_ALIASES", "WINDOW_ICON_ALIASES"]
